version: '3.8'

name: mongodblab

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    command: --bind_ip_all
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "password"

volumes:
  mongodb_data_container:
